### ISSUE TITLE
Top min words topics table is empty

### ISSUE THREAD

**Issue by stefan-jung** [oxygenxml/dita-ot-metrics#1]
First: thanks a lot for making this project!

In a first test, the `Top min words topics` table is empty.

![empty-min-words](https://cloud.githubusercontent.com/assets/3266567/22927605/86e13ae8-f2b2-11e6-83fb-746406978259.png)

**Comment by georgebina** [comment]
Hi Stefan! I cannot reproduce this problem. Please try with the flowers sample from oXygen and let me know if you get that there. If yes, then it may be an issue with the way you invoke the transformations. If not, then it may be something specific to your DITA content - maybe in that case you can try to get a cut-down sample that still shows the problem and share that with us/me.
