### ISSUE TITLE
Transmation failed when running from commandline

### ISSUE THREAD

**Issue by sosanai** [oxygenxml/dita-ot-metrics#5]
I can make a report from oXygen, but failed from command line due to missing the dtd.
See [log.txt](https://github.com/oxygenxml/dita-ot-metrics/files/5840780/log.txt) for detial.

My environments are:
- Windows 10
- DITA-OT 3.4.1

**Comment by raducoravu** [comment]
This is a bug in the Apache ANT xml catalog, the problem is discussed here in more details:

https://github.com/dita-ot/dita-ot/issues/3142

I also created a DITA OT plugin as a patch for the problem:

https://github.com/dita-ot/dita-ot/files/2745305/com.oxygenxml.ant.patches.zip
